### PR TITLE
fix(OER/PER): detect choice type always correctly on explicit prefix

### LINKED ISSUE #478: Stack overflow in rasn::uper::encode
# Bug

This:
```asn1
Fizz ::= SEQUENCE {
  buzz [1] EXPLICIT CHOICE {
     foo [0] NULL,
     bar [1] NULL,
  },
}
```

```rust
rasn::uper::encode(&Fizz {
    buzz: FizzBuzz::foo(()),
})
```

Crashes with:
```sh
thread 'main' has overflowed its stack
fatal runtime error: stack overflow
```

And stack:
```rust
   6: rasn::enc::Encode::encode_with_tag
             at ~/.cargo/registry/src/cargo.spacex.corp-7feba0638092e023/rasn-0.26.6/src/enc.rs:32:0
   7: <rasn::per::enc::Encoder<_,_> as rasn::enc::Encoder>::encode_explicit_prefix
             at ~/.cargo/registry/src/cargo.spacex.corp-7feba0638092e023/rasn-0.26.6/src/per/enc.rs:1150:13
   8: <rasn_stack_overflow::generated::main::FizzBuzz as rasn::enc::Encode>::encode_with_tag_and_constraints
             at ~/Source/rasn-stack-overflow/src/generated.rs:14:45
   9: rasn::enc::Encode::encode_with_tag
             at ~/.cargo/registry/src/cargo.spacex.corp-7feba0638092e023/rasn-0.26.6/src/enc.rs:37:9
  10: <rasn::per::enc::Encoder<_,_> as rasn::enc::Encoder>::encode_explicit_prefix
             at ~/.cargo/registry/src/cargo.spacex.corp-7feba0638092e023/rasn-0.26.6/src/per/enc.rs:1150:13
  11: <rasn_stack_overflow::generated::main::FizzBuzz as rasn::enc::Encode>::encode_with_tag_and_constraints
             at ~/Source/rasn-stack-overflow/src/generated.rs:14:45
  12: rasn::enc::Encode::encode_with_tag
             at ~/.cargo/registry/src/cargo.spacex.corp-7feba0638092e023/rasn-0.26.6/src/enc.rs:37:9
  13: <rasn::per::enc::Encoder<_,_> as rasn::enc::Encoder>::encode_explicit_prefix
             at ~/.cargo/registry/src/cargo.spacex.corp-7feba0638092e023/rasn-0.26.6/src/per/enc.rs:1150:13
  14: <rasn_stack_overflow::generated::main::FizzBuzz as rasn::enc::Encode>::encode_with_tag_and_constraints
             at ~/Source/rasn-stack-overflow/src/generated.rs:14:45
```

# Versions
* rasn: 0.26.6
* rasn-compiler: 0.10.3

# References

* https://github.com/calder/rasn-stack-overflow

### PR DESCRIPTION
**Pull request by Nicceboy**
Adds proper detection for choice type. 
Fixes #478

### CODE REVIEW

File: src/types.rs [hunk 1]
```diff
@@ -83,6 +83,12 @@ pub trait AsnType {
     fn is_present(&self) -> bool {
         true
     }
+    /// Whether the type is choice type.
+    ///
+    /// Custom implementation is only used for `CHOICE` type.
+    fn is_choice() -> bool {
```
Comment (XAMPPRocky) [inline src/types.rs:89]: Should this be an associated constant rather than a function? It seems like something that doesn't needs to be a function.

**Comment by XAMPPRocky** [comment]
Thank you for your PR!
