### PR TITLE
fix: Run clippy and rustdoc only on stable channel in CI

### LINKED ISSUE #334: CI isn't running clips or rustdoc checks
The if statement here doesn't seem working.

https://github.com/librasn/rasn/blob/13a77597156ae57a8f90024bf6696f7abebcea1a/.github/workflows/rust.yml#L91-L94

### PR DESCRIPTION
**Pull request by Nicceboy**
Fixes #334 , at least I hope so.

### CODE REVIEW

**Comment by Nicceboy** [comment]
The root level `--workspace` parameter does not catch all the warnings in standards, and I have to check each of them separately. I am not sure if this is a bug or if I am missing something.

**Comment by Nicceboy** [comment]
I could not find a PR or issue, but this was not problem for with the beta version anymore.

File: src/error/encode.rs [hunk 1]
```diff
@@ -1,5 +1,5 @@
 //! Error types associated with encoding to ASN.1 codecs.
-#![expect(missing_docs)]
+#![allow(missing_docs)]
```
Comment (XAMPPRocky) [inline src/error/encode.rs:2]: This should be expect because it should be removed when it is no longer true.

Comment (Nicceboy) [reply src/error/encode.rs:2]: It fails the pipeline alone with:

```
error: this lint expectation is unfulfilled
 --> src/error/encode.rs:2:11
  |
2 | #![expect(missing_docs)]
  |           ^^^^^^^^^^^^
  |
  = note: `-D unfulfilled-lint-expectations` implied by `-D warnings`
  = help: to override `-D warnings` add `#[allow(unfulfilled_lint_expectations)]
  ```
  
  Should we add `#[allow(unfulfilled_lint_expectations)]` as well to the module?

Comment (Nicceboy) [reply src/error/encode.rs]: I improved the error documentation a bit so that it can be removed. I also removed couple errors since they were not used anymore. There are likely more. Documentation improvements are rather minimal and could be improved in the future.
